name: Send Push Notification

on:
  workflow_dispatch:
    inputs:
      userId:
        description: "User ID"
        required: true
      title:
        description: "Title"
        required: true
      body:
        description: "Body"
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install firebase-admin web-push

      - name: Run Push Script
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PROJECT_ID: shiftori
          VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
        run: |
          node ./scripts/sendPush.js "${{ github.event.inputs.userId }}" "${{ github.event.inputs.title }}" "${{ github.event.inputs.body }}"
